### ISSUE TITLE
归档以后的页面或者点击某个标签后的页面都是没有下一页的按钮

### ISSUE THREAD

**Issue by ghost** [xiangming/landscape-plus#103]
作者你好，
谢谢你做了一个这么精致的主题。
我在使用最新版本的时候发现，文档归档以后的页面或者点击某个标签后的页面都是没有下一页的按钮，也就是比如某个标签下有12篇文章，点了这个标签只能显示10篇（每页设置为10篇）。
不知是我哪里没设置好，还请多指教。
另外生成的静态文件夹中是有第二页的。
我的地址http://jayandjean.github.io/
多谢！

**Comment by 16bh** [comment]
参考这里：http://jimxu.me/2016/07/06/%E8%A7%A3%E5%86%B3hexo%E7%9A%84landscape-plus%E4%B8%BB%E9%A2%98%E6%A0%87%E7%AD%BE%E5%92%8C%E5%BD%92%E6%A1%A3%E6%97%A0%E6%B3%95%E5%88%86%E9%A1%B5%E7%9A%84bug/

**Comment by xiangming** [comment]
Fixed, please reopen if you guys duplicate it.
