### ISSUE TITLE
点击archives时，无法显示分页所有文章归档

### ISSUE THREAD

**Issue by nibnait** [xiangming/landscape-plus#106]
经亲测 在/layout/_partial/archive.ejs的倒数第二行开始 插入

1.    <nav id="page-nav">
2.       <%- paginator({
3.         prev_text: '&laquo; Prev',
4.         next_text: 'Next &raquo;'
5.       }) %>
6.     </nav>

即可。个人博客：http://nibnait.com/ 已成功

**Comment by etnperlong** [comment]
mark，谢谢这个方法，我也在查这个问题

**Comment by sunyanyan** [comment]
借鉴 @nibnait  加了个样式：

`    <nav id="page-nav">
      <%- paginator({
        prev_text: "前一页",
        next_text: "后一页"
      }) %>
    </nav>`

**Comment by sunyanyan** [comment]
点击HOME旁边的archives 能显示所有文章，点击标签下的才不会显示所有文章，尤其用了多个标签的文章。

**Comment by xiangming** [comment]
你们有空发一个PR吗？

**Comment by xiangming** [comment]
Fixed, please reopen if you guys duplicate it.
