### ISSUE TITLE
分享图标出不来

### ISSUE THREAD

**Issue by 16bh** [xiangming/landscape-plus#109]
![image](https://cloud.githubusercontent.com/assets/13450647/16685404/80ba2878-453d-11e6-8dc5-9e0e4444d872.png)
如上图所示，有人碰到过吗

**Comment by HipHopCoderS** [comment]
这个因为字体库文件加载的问题没有加载出来的原因，可以更新下字体库文件试试

**Comment by 16bh** [comment]
更换域名后问题自动修复了
