### ISSUE TITLE
分享功能失效?

### ISSUE THREAD

**Issue by Smalldy** [xiangming/landscape-plus#111]
多说和这个分享冲突?
现在的情况是 点击图标没有任何反应,点击+也没有反应

**Comment by Smalldy** [comment]
而且...在没有readmore之前下方的分享 变成了谷歌推特和脸书...........

**Comment by Smalldy** [comment]
在本地测试可以相应 部署到github上响应不能

**Comment by Smalldy** [comment]
解决

**Comment by disinuo** [comment]
请问是怎么解决的呀。。~我也遇到了同样的问题

**Comment by xiangming** [comment]
@Smalldy 问题解决了吗？方便描述一下，方便其他人吗？

**Comment by Smalldy** [comment]
很久以前的事情了 = = 
总之,需要明白的是,多说可能是不稳定的,有时候js会哦家在不出来
这是多说的锅
另外推荐在coding.net上搭建hexo 因为是国产的 速度很快~
