### ISSUE TITLE
求助：本地预览一切正常，但提交到github pages后小图标不显示了

### ISSUE THREAD

**Issue by flystarhe** [xiangming/landscape-plus#112]
例如右上角的RSS、Search等图标显示成奇怪的符号了，这里面好像没法上传截图，只有麻烦点击下面网址
url：https://flystarhe.github.io/

还有，像评论、分享到等小图标都不显示了。
运行`hexo s`预览显示都是ok的，`hexo d`到github就有问题了，麻烦了

**Comment by disinuo** [comment]
同！！！
求解答

**Comment by xiangming** [comment]
@disinuo 
应该与 #114 有关，已经修复。

**Comment by flystarhe** [comment]
thanks
