### ISSUE TITLE
http://libs.useso.com/js/font-awesome/4.2.0/fonts/fontawesome-webfont加载特别慢

### ISSUE THREAD

**Issue by hotfireeagle** [xiangming/landscape-plus#114]
貌似是360网站卫士停掉了前端专用库这个服务？
详见：http://wangzhan.360.com/notice/detail4

**Comment by phith0n** [comment]
useso最近关服务了，有解决方案么

**Comment by stantang986** [comment]
能否换成https://fonts.googleapis.com啊？这个问题不解决网站没法开啊

**Comment by hotfireeagle** [comment]
hexo博客目录里面的public\vendors\font-awesome\fonts这个目录里面貌似有fontawesome的相关文件，所以我就把主题目录里面的_variables.styl这个文件给修改了一下。找到font部分中的font-icon-path属性，修改为：font-icon-path = "../vendors/font-awesome/fonts/"。总之和字体、图标相关的文件貌似就是在style.styl和_variables.styl这两个文件中。好像这样可以解决加载慢的问题，并且图标也可以出现。

**Comment by hotfireeagle** [comment]
hexo博客目录里面的public\vendors\font-awesome\fonts这个目录里面貌似有fontawesome的相关文件，所以我就把主题目录里面的_variables.styl这个文件给修改了一下。找到font部分中的font-icon-path属性，修改为：font-icon-path = "../vendors/font-awesome/fonts/fontawesome-webfont"。总之和字体、图标相关的文件貌似就是在style.styl和_variables.styl这两个文件中。好像这样可以解决加载慢的问题，并且图标也可以出现。我是前端菜鸟，说错请谅解

**Comment by hu-zhi-hang** [comment]
可以把静态库换成七牛的，/themes/landscape-plus/source/css/_variables.styl

`font-icon-path = "http://cdn.staticfile.org/font-awesome/4.2.0/fonts/fontawesome-webfont"`
