### ISSUE TITLE
更换评论模块

### ISSUE THREAD

**Issue by inkydragon** [xiangming/landscape-plus#119]
多说已死 [重要通知: 多说即将关闭](http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241)

>因公司业务调整，非常遗憾的向大家宣布多说项目即将关闭。 我们将于**2017年6月1日正式关停服务**，在此之前您可以通过后台的数据导出功能导出自己站点的评论数据。 对此给您造成的不便，我们深表歉意，感谢您的一路相伴。

----
可选替代品：
- 换回Disqus
- [网易云跟帖](https://gentie.163.com/index.html)
   支持https
- [来必力](http://www.laibili.com.cn/)
   支持https
- [畅言](http://changyan.kuaizhan.com/)
   搜狐旗下产品
- [友言](http://www.uyan.cc/getcode)
- 用Firebase自己搞一个
   [Self-host comments in Jekyll, powered by Firebase real-time database](https://flinhong.com/2017/03/25/self-host-comments-in-jekyll-using-firebase-database/)    
   [Jekyll 中使用 Firebase/Wilddog 部署评论系统](http://www.jithee.name/blog/post/75/)

各方案评价参考：
[如何评价“多说”即将关闭？有什么替代方案？](https://www.zhihu.com/question/57426274)

**Comment by leveychen** [comment]
强烈建议加入 网易云根帖。。。

**Comment by xiangming** [comment]
多说关闭了，意外且遗憾，欢迎发起Pull request。

**Comment by fengfu** [comment]
网易云跟帖也要关闭了……

**Comment by 15b883** [comment]
建议选择畅言~~
