### ISSUE TITLE
请问一下如何将主页的文章显示摘要，而不是显示整篇文章。

### ISSUE THREAD

**Issue by ThomasLeedev** [xiangming/landscape-plus#121]
此主题会将博客的所有文章都显示在主页，然后每篇文章都是全文显示的。

感觉这样子不太好，如果可以自定义显示的文章，或者只显示文章的摘要就好了。

不知道有没有办法可以配置或是否可以更换博客的主页呢？

小白提问，期待大神的回答。

**Comment by UGxhdHlwdXM** [comment]
可以在希望展示的内容后面加上`<!--more-->`

**Comment by ThomasLeedev** [comment]
@PlatypusPro 非常感谢。

通过在想显示的段落后面加上 `<!--more-->` 就可以在主页中只显示前面的段落了。

**Comment by ThomasLeedev** [comment]
@PlatypusPro 能再请教一个问题吗？我是否可以选择不显示某一篇文章呢，还有文章的优先级是否可以选择？十分感谢。

**Comment by UGxhdHlwdXM** [comment]
只要不是用`hexo new`（默认是`post`）新建的文章，比如直接在`source`文件夹下新建`.md`文件或者用`hexo new page`什么的，应该就不会在主页显示…
然后主页文章的顺序应该和[hexo-generator-index](https://github.com/hexojs/hexo-generator-index)这个模块有关，默认是按`-date`排序也就是从新到旧，大概可以给每个文章加个权值然后改一下排序的关键字什么的（我猜的），剩下的我就不知道了……不会`Node.js`QAQ

**Comment by ThomasLeedev** [comment]
@PlatypusPro 好的，谢谢啦。
