### ISSUE TITLE
字体和生成速度问题

### ISSUE THREAD

**Issue by qilicun** [xiangming/landscape-plus#13]
你好，我用了这个主题，发现文章的字体也是黑体那样子看着有点须虚不是很舒服，怎样修改成原来主题的字体？
另外用默认的主题生成速度大概是3s不到，用了这个主题生成速度特别慢，大概超过40s，请问是那个插件或者配置托慢了速度吗？
谢谢

**Comment by tsaoshuang** [comment]
怎么修改成 首页文章显示摘要啊？

**Comment by chinamobiler** [comment]
找到 index.ejs  修改成摘要
