### ISSUE TITLE
请问怎么折叠文章

### ISSUE THREAD

**Issue by giantbranch** [xiangming/landscape-plus#130]
就是文章太长了，希望可以只显示前面150字左右，下面有**点击查看更多**的按纽

**Comment by UGxhdHlwdXM** [comment]
在你`.md`文件里想折叠的地方加`<!--more-->`

**Comment by giantbranch** [comment]
没有自动的吗......

**Comment by UGxhdHlwdXM** [comment]
那就在这个`div`里自己改一下 主题不带一定字数自动折叠这个功能
https://github.com/xiangming/landscape-plus/blob/22826764f0e41c24ea8b0c5aeedaacc614e80c61/layout/_partial/article.ejs#L13

**Comment by giantbranch** [comment]
好吧
