### ISSUE TITLE
Comments 跳转到bookmark.com

### ISSUE THREAD

**Issue by GasonW** [xiangming/landscape-plus#131]
请问为什么点击文章的comments之后会跳转到一个www.bookmark.com的网页？如何去除此链接？

**Comment by UGxhdHlwdXM** [comment]
有BLOG链接吗

**Comment by GasonW** [comment]
十分抱歉！我查到问题的原因了，不是主题的原因。我看了一下源码，comment下有一个连接，指向www.yoursite.com/xxxx， 这个链接会跳转到www.bookmark.com去，我已经在_config.yml中将url设置为了自己的blog域名，现在没有问题了。
感谢作者提供了这么好的主题！
