### ISSUE TITLE
为什么我的archives页面的文章没有按年份分组，而是和首页相同？

### ISSUE THREAD

**Issue by xingxiudong** [xiangming/landscape-plus#24]
为什么我的archives页面的文章没有按年份分组和仅仅显示标题，而是和首页相同？

页面：http://xingxiudong.com/archives/

正确的效果应该是这样的：http://silenceage.com/archives/

是不是要加什么配置？

**Comment by xiangming** [comment]
我先关掉这条，如果还有问题你再reopen。
