### ISSUE TITLE
最近日子不太平

### ISSUE THREAD

**Issue by YumeMichi** [xiangming/landscape-plus#3]
别说Google了，连CloudFlare也跪了。。。大陆、宝岛都跪

**Comment by leeethe** [comment]
说道cdn，http://www.bootcdn.cn/可以否？

**Comment by imruxin** [comment]
@leeethe 之前有简单的收集一下。

**CDN**

- [jQuery](http://code.jquery.com)
- [360前端公共库](http://libs.useso.com/)
- [新浪SAE](http://lib.sinaapp.com/)
- [百度CDN](http://cdn.code.baidu.com/)
- [又拍云CDN](http://jscdn.upai.com/)
- [staticfile](http://www.staticfile.org/)
- [CDNJS](http://cdnjs.com/libraries/jquery/)

**Comment by leeethe** [comment]
多谢这个整理，还蛮有用。

**Comment by imhentai** [comment]
觉得还是换个cdn比较好...新浪或者七牛的都可以啊
