### ISSUE TITLE
主页的归档的时间格式问题

### ISSUE THREAD

**Issue by eexpress** [xiangming/landscape-plus#36]
显示成 November 2014，找半天没找到修改的地方。难道是不能修改？想改成中文习惯的显示。甚至改成时间线的格式，比如：
2014年11月........................8
文章数量右对齐。

**Comment by qinyuanpei** [comment]
@myqianlan 我从Hexo的文档中找到了，可是我不知到怎么改？

**Comment by fengzixu** [comment]
我在用这个主题的时候archives点击之后，显示的文章数量不对，少了很多文章。是怎么回事

**Comment by xiangming** [comment]
@fengzixu 试试重新生成`hexo cl && hexo g`

另外检查下你的配置文件**_config.yml*

**Comment by xiangming** [comment]
Fixed, please reopen if you guys duplicate it.
