### ISSUE TITLE
设置mathjax模块的开关

### ISSUE THREAD

**Issue by myqianlan** [xiangming/landscape-plus#37]
由于mathjax响应速度略慢，所以不需要的用户可以如此设置开关。
同样希望作者把这个加上去，由于太简单，我就不发request了。
设置如下：

在_config.yml里面加一句
```javascript
mathjax: false
```
在after-footer.ejs里面将
```javascript
<%- partial('mathjax') %>
```
换成
```javascript
<% if (theme.mathjax){ %>
  <%- partial('mathjax') %>
<% } %>
```

**Comment by xiangming** [comment]
Closed by [this pulll request](https://github.com/xiangming/landscape-plus/pull/39)
我先关掉这条，如果还有问题你再reopen。
