### ISSUE TITLE
代码高亮的修改方式？

### ISSUE THREAD

**Issue by crescentluna** [xiangming/landscape-plus#43]
关于代码高亮，我看hexo的介绍说是用的highlight.js，但是并没有找到对应的文件哈，想请问下代码高亮是在哪里修改的。

**Comment by xiangming** [comment]
@crescentluna @nshen 你们可以尝试去[hexo官方repo](https://github.com/hexojs/hexo/)问一下，我也不知能否支持`SyntaxHighlighter`。

**Comment by xiangming** [comment]
我先close，如果还有问题，你们再reopen.
