### ISSUE TITLE
nocss.css加载失败

### ISSUE THREAD

**Issue by AxisRay** [xiangming/landscape-plus#45]
首先感谢你这个hexo主题
我在优化站点加载速度的时候发现有个样式表nocss.css一直加载失败
后检查后发现根本没有这个nocss.css
我搜索后在after-footer.ejs中的百度分享的代码中发现这个nocss.css
但是删除后分享功能会出问题

**Comment by xi3** [comment]
很喜欢这个模板，这个错误怎么去掉才好呢？

**Comment by nshen** [comment]
现在来一个bug就让自己改。。其他人怎么办。。。
有没有大神改掉大家都跟着受益呀，顺便把百度去掉换成多说分享，跟多说评论一起管理多好呀

**Comment by xiangming** [comment]
已解决
