### ISSUE TITLE
多说评论框不能加载。

### ISSUE THREAD

**Issue by iBenjamin** [xiangming/landscape-plus#47]
我试了用多说id：10368340 和 多说用户名都不能加载到。我的小站：http://ibenjamin.github.io/

**Comment by hilushan** [comment]
1、注册多说的时候，会注册类似hexoblog.duoshuo.com的域名。hexoblog为举例。
2、把hexoblog字段添加到landscap-plus的配置文件中。
3、hexo g并提交后，清除下浏览器缓存然后再试。

希望能解决你的问题。

**Comment by iBenjamin** [comment]
可以了，非常感谢。

**Comment by lizhengnacl** [comment]
@hilushan 受教了。
