### ISSUE TITLE
多说配置无效

### ISSUE THREAD

**Issue by zhiqiu** [xiangming/landscape-plus#48]
我按照教程加上多说id,但是点comment之后跳转到http://sp3.yousee.com/，我的blog是zhiqiu.github.io

**Comment by zhiqiu** [comment]
抱歉，应该是主页无效，但是文章页可以，请问如何修改？或者主页不显示comment框？

**Comment by xiangming** [comment]
@zhiqiu 主题文件里面没有这个网址`http://sp3.yousee.com/`，你的主题是从Github上clone的吗？

建议你删除主题，在你的hexo目录执行下面的命令重新clone：
```
git clone https://github.com/xiangming/landscape-plus.git themes/landscape-plus
```

**Comment by zhiqiu** [comment]
可能是延迟还是什么，现在已经ok了，谢谢。另外，hexo的缩进好像也有点问题，我在```和```之间的代码如果有缩进，编译后会变成双倍缩进。

**Comment by vitalzhu** [comment]
你好，我也在多说评论上遇到点问题。
我的问题是按照教程上的步骤做完后，出现评论的按钮，但是无法出现评论的输入框相关内容。

我的博客地址是：[http://vitalzhu.github.io/](http://vitalzhu.github.io/)

**Comment by zhiqiu** [comment]
你现在还是之前的comment，没有改为多说。你再按教程设置一下看看。

**Comment by xiangming** [comment]
@vitalzhu 我刚刚看你的博客地址，已经正常了。

**Comment by xiangming** [comment]
我先关掉这条，如果还有问题你再reopen。

**Comment by vitalzhu** [comment]
多谢！我的原因是只配置了Hexo的配置文件，但是没有在多说上申请新站点的后台，希望可以帮到其他人！
