### ISSUE TITLE
希望目录分类目录是摘要或列表模式

### ISSUE THREAD

**Issue by flystarhe** [xiangming/landscape-plus#49]
现在 landscape-plus 的文章列表是 全文顺序排列，对于阅读和查看旧的文章非常不利，希望文章列表可以是摘要方式，而非全文。
如果实在不行 其实就简单的文章标题列表也会好些。

**Comment by javatmn** [comment]
Add below tags  in your blog:

<!— more —>
Summary block…
…..
<!— more —>

Then you can get what you needed.

Check my blog http://jtmnblog.us.to for an example.

Cheers!
Yong

From:  Jian <notifications@github.com>
Reply-To:  xiangming/landscape-plus
<reply+00928317ec545dffea29cfb8db4fe8e4e2eaf5f83345b69892cf0000000110cc7e469
2a169ce033a5ac5@reply.github.com>
Date:  Tuesday, January 13, 2015 at 2:33 PM
To:  xiangming/landscape-plus <landscape-plus@noreply.github.com>
Subject:  [landscape-plus] 希望目录分类目录是摘要或列表模式 (#49)


现在 landscape-plus 的文章列表是 全文顺序排列，对于阅读和查看旧的文章非常不
利，希望文章列表可以是摘要方式，而非全文。
如果实在不行 其实就简单的文章标题列表也会好些。

—
Reply to this email directly or view it on GitHub
<https://github.com/xiangming/landscape-plus/issues/49> .

**Comment by flystarhe** [comment]
thanks, very good.

**Comment by xiangming** [comment]
我先关掉这条，如果还有问题你再reopen。
