### ISSUE TITLE
代码缩近采用tab的问题

### ISSUE THREAD

**Issue by JeremyHe-cn** [xiangming/landscape-plus#50]
当在代码块中使用tab进行缩近时，在md显示正常，但是发布出来后，缩近太长了，长度超过了四个空格。请问这个要怎么解决 ？修改哪里呢？

具体看图:
![](http://ntu.so/di/U80FB/2015-01-16_10:25:17的屏幕截图.png)

或者看我的文章示例也行
  > [示例](http://www.j-cn.me/2015/01/15/09_Android-Webview%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%BB%93/)

**Comment by xiangming** [comment]
应该是你的编辑器设置问题，网上搜索一下怎么配置你编辑器的`tab_size`

**Comment by JeremyHe-cn** [comment]
这个跟编辑器没关系，我用vim,geany,gedit都一样，只要缩进使用tab，而不是空格就出现这种情况。
但是写代码的时候一般都是用tab，而不是使用4个空格

**Comment by xiangming** [comment]
@JeremyHe-cn 将编辑器设置为tab自动转换为4空格，这是一个很好的习惯。

**Comment by JeremyHe-cn** [comment]
不同公司要求不一样，不同语言默认的TAB也不一样，例如JAVA默认的就是一个TAB字符，而python则一般是2个空格。所以要做的并不是强制要求把TAB转4个空格，而是想办法做兼容。

回到问题本身，如果您没有时间解决，麻烦可否指点一下思路，我尝试一下。:)

**Comment by xiangming** [comment]
@JeremyHe-cn 刚查看了代码，主题没有去处理这一块，是`<pre>`正常输出。
你可以去[hexo官方](https://github.com/hexojs/hexo)提问。
