### ISSUE TITLE
如何关闭article-gallery

### ISSUE THREAD

**Issue by JeremyHe-cn** [xiangming/landscape-plus#60]
我发现只要我文章里有图片，那么article-gallery会出现在标题的上面，请问怎么关掉呢？

具体的步骤如下：
文章中使用```![](图片url)```
进入相应的文章后，显示正常。然后按F5刷新，标题上边就会出现和文章里一样的图片，

看了一下，发现是article-gallery标签的。

**Comment by JeremyHe-cn** [comment]
我现在的解决办法是在文章里里加入
```
photos:
- 
```
加入这段之后，post.photos.forEach(function(photo, i)就不会把文章内的图片弄到标题前面了

**Comment by nshen** [comment]
我之前都不知道那是什么怪东西，然后到html里把那段删了。。。

**Comment by JeremyHe-cn** [comment]
@nshen 如果你在写文章的时候加入
```
photos:
- 图片1url
- 图片2url
```

你会发现，这个怪东西是挺漂亮好看的^_^
只是现在这个功能把我文章里的图片也算到photos里了

**Comment by nshen** [comment]
对，我没加那两句，文章里插图，自动跑到上边做切换了，我不用那功能，直接删了html，目前没啥影响

**Comment by xiangming** [comment]
我先close，如果还有问题，你们再reopen.
