### ISSUE TITLE
关闭百度分享后，原主题自带的分享功能显示不正常

### ISSUE THREAD

**Issue by TrustyWolf** [xiangming/landscape-plus#61]
RT.
baidushare: false
.js文件是起作用的，但是显示不正常。

**Comment by nshen** [comment]
我那里首页看还有报错这个没加载上

http://nsclick.baidu.com/v.gif?pid=307&type=3071&sign=&desturl=http%253A%252F%252Fwww.nshen.net%252Farticle%252F2014-12-05%252Fgrunt-ts%252F&linkid=i5tncnsx23o&apitype=1

**Comment by xiangming** [comment]
我先close这条，如果还有问题，你可以reopen。
