### ISSUE TITLE
hexo generate 时没有更新style.css

### ISSUE THREAD

**Issue by xbin999** [xiangming/landscape-plus#62]
hexo generate 后发现生成的style.css没有采用lanscape-plus的CSS。

不太确定是何时出现该问题的，搜了一下看到有说[hexojs/hexo-renderer-stylus#5](https://github.com/hexojs/hexo-renderer-stylus/issues/5) 有问题，但我看了自己采用的版本就是hexo-site@2.8.3 和hexo-renderer-stylus@0.1.0。

不一定是landscape-plus的问题，求助一下。

**Comment by xbin999** [comment]
我自己搞错了，需要删除public/css/style.css，才会重新生成style.css。

**Comment by xiangming** [comment]
@xbin999 可以尝试`hexo clean`命令，比手动删方便。
