### ISSUE TITLE
没有多说评论框

### ISSUE THREAD

**Issue by evanzh7** [xiangming/landscape-plus#69]
hexo: 3.0.1
os: Darwin 14.3.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

landscape-plus/_config.yml 已经填写多说shortname
主题安装完成后没有多说框。

**Comment by xiangming** [comment]
有网址可以测试吗？
你看看console有没有js报错。

**Comment by evanzh7** [comment]
测试网址 evanzh7.github.io

**Comment by xiangming** [comment]
你的测试网址还没有升级hexo 3.0.1 对不对？

**Comment by xiangming** [comment]
我刚在本地升级了hexo 3.0.1，在landscape-plus/_config.yml 填写多说shortname后，是有多说评论框的。

你确定你填写的shortname是正确有效的吗？

**Comment by xiangming** [comment]
我先close这条，如果你还有问题，你再reopen.

**Comment by evanzh7** [comment]
好的 ，问题已经解决，是我的问题，主题没问题。
