### ISSUE TITLE
你好，请问 Landscape-plus 能否集成社交按钮（微博，知乎，简书，豆瓣，github等等），显示在右上角RSS图标的前方？

### ISSUE THREAD

**Issue by jerry011235** [xiangming/landscape-plus#74]
你好，请问 Landscape-plus 能否集成社交按钮（微博，知乎，简书，豆瓣，github等等），显示在右上角RSS图标的前方？
![](http://i.imgur.com/bXf1nl2.png)
然后类似[jacman主题](https://github.com/wuchong/jacman)，在主题的_config.yml文件中添加:
``` bash
#### 作者信息
author:
  intro_line1:  "Hello ,I'm Larry Page in Google."    ## 网站底部的个人介绍
  intro_line2:  "This is my blog,believe it or not."  
  weibo_verifier:  ## 微博秀的验证码
  tsina:           ## 用于微博秀和微博分享
  weibo:           ## 用于显示网站底部社交按钮，下同
  douban:         
  zhihu:  
  email:     
  twitter:   
  github:     
  facebook: 
  linkedin:   
  google_plus:   
  stackoverflow:  
```

**Comment by PlatypusPro** [comment]
可以的，但是现在还不能直接加载`_confing.yml`里，你可以在`\layout\_partial\header.ejs`里的`<nav id="sub-nav">`下仿照样式添加，然后查一下你要加的图标的`font-awesome`的图标代码，加到`\source\css\_partial\header.styl`里，直接仿照`RSS`那样的格式即可

**Comment by xiangming** [comment]
@jerry011235 你可以按照 @PlatypusPro 说的试试。

**Comment by jerry011235** [comment]
谢谢！我试一下。
