### ISSUE TITLE
主题配置文件里google+账号要怎么配置

### ISSUE THREAD

**Issue by weaming** [xiangming/landscape-plus#77]
如题

**Comment by PlatypusPro** [comment]
这个是[原主题](https://github.com/hexojs/hexo-theme-landscape/blob/master/_config.yml)`landscape`自带的，好像没什么用...

**Comment by weaming** [comment]
@PlatypusPro 呃

**Comment by xiangming** [comment]
默认是支持Google+分享的，你可以试试。
