### ISSUE TITLE
新版3.0 hexo下archives无法全部显示

### ISSUE THREAD

**Issue by grasses** [xiangming/landscape-plus#79]
hexo generater分页问题，只能显示部分archives，无法全部显示。
能否解决？

**Comment by jerry011235** [comment]
目前只能做如下设置，即关闭分页，另外设置每页显示文章数是一个很大的数字（我设置为100），基本能满足需要。参考我的博文：http://starsky.gitcafe.io/2015/05/18/Hexo%E5%88%86%E9%A1%B5%E8%AE%BE%E7%BD%AE%E7%9A%84%E9%97%AE%E9%A2%98/

**Comment by grasses** [comment]
感谢楼主，谢谢分享。

**Comment by sonicrang** [comment]
http://wurang.me/2016/01/25/hexo_pagination/  我修改了一部分代码

**Comment by xiangming** [comment]
Fixed, please reopen if you guys duplicate it.
