### ISSUE TITLE
如何更改搜索引擎为谷歌

### ISSUE THREAD

**Issue by weaming** [xiangming/landscape-plus#80]
如何更改搜索引擎为谷歌

**Comment by whzecomjm** [comment]
同问

**Comment by xiangming** [comment]
请参考这个issue： https://github.com/xiangming/landscape-plus/issues/2

**Comment by weaming** [comment]
百度没收录，我自己添加了google搜索框，这个示例查看 http://i.weaming.info/ ，谷歌已收录，是可以搜到结果的
