### ISSUE TITLE
怎么自定义顶部的图片

### ISSUE THREAD

**Issue by shikelong** [xiangming/landscape-plus#81]
thx

**Comment by shikelong** [comment]
修改 banner_url 变量地址并且在相关文件夹下增加图片。

**Comment by xiahei** [comment]
表示无果，能再 详细些？
**THX!**

**Comment by shikelong** [comment]
@xiahei  或者你在项目的资源文件夹里面找到顶部的图片。然后把你要替换的图片拉进和原顶部图片同级的文件夹。然后把你的替换图片的名字改成和原图片一样的就行了。

**Comment by xiahei** [comment]
@shikelong get， THX！
