### ISSUE TITLE
请问怎么正确的启用多说评论？

### ISSUE THREAD

**Issue by shikelong** [xiangming/landscape-plus#82]
谢谢。不知道duoshuo_shortname的值应该写什么？

我在_config.yml里面添加了

duoshuo_shortname: shikelong

然后hexo d以后。点击评论会跳转到

http://144.dragonparking.com/?site=yoursite.com&t=1435911468&s=2b2de72b164c66d8ba2cb239feb3e1d5#ds-thread

我的多说注册情况
![qq 20150703161925](https://cloud.githubusercontent.com/assets/4499997/8495329/579f1e20-219f-11e5-8a82-4ac2eefb921d.png)

@xiangming

**Comment by xiangming** [comment]
看样子是你的hexo站点地址没配置正确，在hexo的_config.yml里面找到这个代码：
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```
yoursite.com要换成你的博客地址。

**Comment by shikelong** [comment]
我把url的值换成我的博客地址了 `http://xxx.github.io`。。然后现在点击评论报错了。 

```bash

GET http://shikelong.duoshuo.com/api/threads/listPosts.json?thread_key=2015%2F0…ead%2Clog%2CextraCss&referer=http%3A%2F%2Fshikelong.github.io%2F&v=15.4.27 400 ({Bad Request})
```
```bash
出错啦(990002): 参数错误
```



@xiangming

**Comment by shikelong** [comment]
好了
