### ISSUE TITLE
tag页面显示不全

### ISSUE THREAD

**Issue by icepy** [xiangming/landscape-plus#85]
点击Tag标签未显示全，本身我的iOS分类有30篇博文，但是只显示了5篇

[http://icepy.github.io/tags/iOS/](http://icepy.github.io/tags/iOS/)

如果是我设置不对，还望告诉一下，谢～

**Comment by xiangming** [comment]
刚看了你博客，是30篇~

**Comment by icepy** [comment]
@xiangming  因为你的tag跟per_page属性有关系，本来我预期是首页只放五篇文章，per_page设置成5，Tag就只显示5个，我现在per_page设置成了0，你在渲染Tag的时候是不是引用了per_page变量。

**Comment by xiangming** [comment]
Fixed, please reopen if you guys duplicate it.
