### ISSUE TITLE
希望增加全站https的选项

### ISSUE THREAD

**Issue by xseven007** [xiangming/landscape-plus#87]
希望增加全站https的选项，因为layout目录下一些脚本含有非SSL连接的地址，导致一些站点无法全站https，另外百度分享的JS脚本居然没有https的连接，360的字体库不支持https，考虑更换ustc或者其他的CDN可能更好

**Comment by leveychen** [comment]
同求。希望增加Disqus。多说目前来说没办法https，因为引用了新浪的头像。。。。

**Comment by JayceChant** [comment]
我提了一个pull request 解决 MathJax 和 百度分享 的https 问题
https://github.com/xiangming/landscape-plus/pull/107

其实只要去掉协议头，浏览器会自动根据当前的协议补全。

**Comment by JayceChant** [comment]
Disqus 本身就支持，只是在 _config.yml 里没有给出示例而已
只要在根目录的 _config.yml 加上
```
disqus_shortname: your_shortname
```
Landscape-plus 是支持Disqus的。
因为目前没有读 theme 的配置，所以写在主题的配置文件无效。
等作者合了我的[PR](https://github.com/xiangming/landscape-plus/pull/107)就好了

**Comment by xiangming** [comment]
@JayceChant 
Well done, dude!
Merged!
