### ISSUE TITLE
为何我的代码高亮好像用不了

### ISSUE THREAD

**Issue by LionSR** [xiangming/landscape-plus#95]
http://lionsr.com/2016/01/19/Coffeecup-and-mass/

**Comment by 16bh** [comment]
``` c
```

要类似这样输入代码

**Comment by 16bh** [comment]
参考这里：http://jimxu.me/2016/07/07/landscapse-plus%E4%B8%BB%E9%A2%98%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE%E6%B5%8B%E8%AF%95/

**Comment by xiangming** [comment]
正确使用markdown代码语法：
\`\`\`php
your code here
\`\`\`
