### ISSUE TITLE
切换语言版本问题

### ISSUE THREAD

**Issue by zhanglongxiang** [xiangming/landscape-plus#99]
切换语言版本，按照要求在站点的配置文件_config.yml，修改language:配置项。可是我看到在_config.yml，没有language项，我加上了一行language: zh-CN 也不管用，还是繁体。

**Comment by xiangming** [comment]
在站点的配置文件`_config.yml`，修改`language:`配置项，zh-CN为中文简体，zh-TW为中文繁体，default为英文。
不是主题的`_config.yml`哦。
